version: '3'

services:
  teamspeak:
    image: mbentley/teamspeak
    restart: always
    container_name: teamspeak
    environment:
      - TS3SERVER_LICENSE=accept
    ports:
      - '9987:9987/udp'
      - '30033:30033'
      - '10011:10011'
      - '41144:41144'
    volumes:
      - teamspeak-data:/data

volumes:
  teamspeak-data:
